In [58]:
%matplotlib qt

In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


EEGsignal = pd.read_csv('5_1.tdt', sep = '\t')

In [65]:
EEGsignal['O2-AVE'].plot()
plt.show()

In [60]:
from scipy import stats

zscore = np.abs(stats.zscore(EEGsignal))

In [61]:
zscore

array([[3.17899489e-04, 9.56486958e-04, 5.58508816e-04, ...,
        1.92042531e-04, 3.90504101e-04, 5.10923144e-04],
       [5.04602148e-03, 3.93355040e-03, 1.37416734e-03, ...,
        8.25044705e-03, 3.65411902e-03, 5.63817712e-03],
       [3.54183231e-02, 2.51178270e-02, 1.10715938e-02, ...,
        5.76144842e-02, 2.51067824e-02, 3.70790228e-02],
       ...,
       [6.76610939e-01, 6.51764819e-01, 7.04263833e-01, ...,
        5.36125118e-01, 9.87474155e-01, 5.71927374e-01],
       [5.80699247e-01, 5.61996107e-01, 5.50305265e-01, ...,
        2.98614146e-01, 9.04281334e-01, 6.90500445e-01],
       [5.36382207e-01, 4.12373267e-01, 4.16955306e-01, ...,
        1.59654844e-02, 7.58912117e-01, 7.07132740e-01]])

In [62]:
EEGsignal_cleaned = EEGsignal[(zscore < 3).all(axis=1)]

In [63]:
EEGsignal_cleaned = EEGsignal_cleaned.drop('Fz-AVE', axis = 1)

In [64]:
EEGsignal

FP1-AVE   FP2-AVE    F3-AVE    F4-AVE    C3-AVE    C4-AVE    P3-AVE  \
0      0.000000  0.000000 -0.000000  0.000000  0.000000  0.000000  0.000000   
1      0.033760  0.020392 -0.013170  0.042574 -0.065139 -0.015834  0.050228   
2      0.250626  0.165498 -0.079252  0.288474 -0.484097 -0.151652  0.349213   
3      0.839319  0.631318 -0.187216  0.864743 -1.637460 -0.674957  1.077871   
4      1.667625  1.504604 -0.173452  1.503274 -3.359195 -1.881725  1.941490   
...         ...       ...       ...       ...       ...       ...       ...   
16564 -6.662706 -4.494320 -7.253375 -3.422197 -9.333989 -4.161500 -3.728463   
16565 -5.851017 -4.599483 -6.059617 -3.500802 -8.156602 -5.703773 -3.293391   
16566 -4.833445 -4.470947 -4.802931 -4.152055 -6.902652 -6.414976 -2.163245   
16567 -4.148611 -3.856058 -3.753798 -4.243930 -5.415472 -6.445921 -0.322112   
16568 -3.832176 -2.831186 -2.845100 -2.806881 -3.459513 -6.123834  2.221299   

         P4-AVE     O1-AVE     O2-AVE    F7-AVE    F8-AVE    T3-AVE    T4-AVE  \
0      0.000000  -0.000000  -0.000000  0.000000  0.000000 -0.000000  0.000000   
1     -0.037272   0.022868   0.080835 -0.051392 -0.012768 -0.067817 -0.011816   
2     -0.295561   0.244327   0.627766 -0.374609 -0.120452 -0.494139 -0.099977   
3     -1.092498   1.195652   2.237212 -1.224636 -0.504243 -1.636522 -0.408991   
4     -2.525722   3.636211   4.908042 -2.371869 -1.243336 -3.303697 -1.112679   
...         ...        ...        ...       ...       ...       ...       ...   
16564  2.505536  20.369928  29.397354 -6.654185 -0.450905 -4.003706  0.079066   
16565 -0.771059  18.333860  27.977976 -5.466195  0.074070 -0.393541 -0.050643   
16566 -3.170910  15.921567  26.831734 -4.853817  0.488236  0.830944 -0.466303   
16567 -4.621101  12.808357  23.866287 -4.465345  1.026725  0.590151 -0.756542   
16568 -5.378993   8.415253  17.278095 -4.029249  2.070968  0.582129 -0.465724   

         T5-AVE     T6-AVE    Fz-AVE    Cz-AVE    Pz-AVE  
0     -0.000000  -0.000000  0.000000  0.000000 -0.000000  
1      0.014627   0.022676  0.066893 -0.024733 -0.054912  
2      0.116563   0.159554  0.476665 -0.187310 -0.391638  
3      0.431627   0.464762  1.502734 -0.642279 -1.236440  
4      1.006983   0.619786  2.711648 -1.308458 -2.219533  
...         ...        ...       ...       ...       ...  
16564 -0.464180  10.776360 -6.329122 -5.965889 -0.203701  
16565  1.298563  12.810404 -5.768032 -7.266098 -3.614621  
16566  2.370281  13.840785 -4.451981 -7.480521 -6.119771  
16567  3.053203  13.404279 -2.480397 -6.850052 -7.389668  
16568  3.516366  11.138851 -0.134124 -5.748385 -7.567797  

[16569 rows x 19 columns]

In [65]:
EEGsignal_cleaned = EEGsignal_cleaned[['FP1-AVE', 'FP2-AVE', 'F3-AVE', 'F4-AVE', 'F7-AVE', 'F8-AVE', 'C3-AVE', 'C4-AVE', 'Cz-AVE', 'T3-AVE', 'T4-AVE', 'T5-AVE', 'T6-AVE', 'P3-AVE', 'P4-AVE', 'Pz-AVE', 'O1-AVE', 'O2-AVE']]

In [66]:
EEGsignal_cleaned

FP1-AVE   FP2-AVE    F3-AVE    F4-AVE    F7-AVE    F8-AVE    C3-AVE  \
0      0.000000  0.000000 -0.000000  0.000000  0.000000  0.000000  0.000000   
1      0.033760  0.020392 -0.013170  0.042574 -0.051392 -0.012768 -0.065139   
2      0.250626  0.165498 -0.079252  0.288474 -0.374609 -0.120452 -0.484097   
3      0.839319  0.631318 -0.187216  0.864743 -1.224636 -0.504243 -1.637460   
4      1.667625  1.504604 -0.173452  1.503274 -2.371869 -1.243336 -3.359195   
...         ...       ...       ...       ...       ...       ...       ...   
16564 -6.662706 -4.494320 -7.253375 -3.422197 -6.654185 -0.450905 -9.333989   
16565 -5.851017 -4.599483 -6.059617 -3.500802 -5.466195  0.074070 -8.156602   
16566 -4.833445 -4.470947 -4.802931 -4.152055 -4.853817  0.488236 -6.902652   
16567 -4.148611 -3.856058 -3.753798 -4.243930 -4.465345  1.026725 -5.415472   
16568 -3.832176 -2.831186 -2.845100 -2.806881 -4.029249  2.070968 -3.459513   

         C4-AVE    Cz-AVE    T3-AVE    T4-AVE    T5-AVE     T6-AVE    P3-AVE  \
0      0.000000  0.000000 -0.000000  0.000000 -0.000000  -0.000000  0.000000   
1     -0.015834 -0.024733 -0.067817 -0.011816  0.014627   0.022676  0.050228   
2     -0.151652 -0.187310 -0.494139 -0.099977  0.116563   0.159554  0.349213   
3     -0.674957 -0.642279 -1.636522 -0.408991  0.431627   0.464762  1.077871   
4     -1.881725 -1.308458 -3.303697 -1.112679  1.006983   0.619786  1.941490   
...         ...       ...       ...       ...       ...        ...       ...   
16564 -4.161500 -5.965889 -4.003706  0.079066 -0.464180  10.776360 -3.728463   
16565 -5.703773 -7.266098 -0.393541 -0.050643  1.298563  12.810404 -3.293391   
16566 -6.414976 -7.480521  0.830944 -0.466303  2.370281  13.840785 -2.163245   
16567 -6.445921 -6.850052  0.590151 -0.756542  3.053203  13.404279 -0.322112   
16568 -6.123834 -5.748385  0.582129 -0.465724  3.516366  11.138851  2.221299   

         P4-AVE    Pz-AVE     O1-AVE     O2-AVE  
0      0.000000 -0.000000  -0.000000  -0.000000  
1     -0.037272 -0.054912   0.022868   0.080835  
2     -0.295561 -0.391638   0.244327   0.627766  
3     -1.092498 -1.236440   1.195652   2.237212  
4     -2.525722 -2.219533   3.636211   4.908042  
...         ...       ...        ...        ...  
16564  2.505536 -0.203701  20.369928  29.397354  
16565 -0.771059 -3.614621  18.333860  27.977976  
16566 -3.170910 -6.119771  15.921567  26.831734  
16567 -4.621101 -7.389668  12.808357  23.866287  
16568 -5.378993 -7.567797   8.415253  17.278095  

[15621 rows x 18 columns]

In [92]:
EEGsignal_cleaned.plot(subplots = True)
plt.show()

In [26]:
EEGsignal_cleaned['O2-AVE'].plot()
plt.show()

In [67]:
EEGsignal_cleaned.drop(EEGsignal_cleaned.tail(21).index, inplace =True)

In [68]:
EEGsignal_cleaned_stacked = pd.melt(EEGsignal_cleaned)

In [69]:
EEGsignal_cleaned_stacked

variable      value
0       FP1-AVE   0.000000
1       FP1-AVE   0.033760
2       FP1-AVE   0.250626
3       FP1-AVE   0.839319
4       FP1-AVE   1.667625
...         ...        ...
280795   O2-AVE  25.142361
280796   O2-AVE  19.643417
280797   O2-AVE  13.450405
280798   O2-AVE   7.403413
280799   O2-AVE   2.315274

[280800 rows x 2 columns]

In [70]:
EEGsignal_cleaned_stacked['variable'] = EEGsignal_cleaned_stacked['variable'].replace(['FP1-AVE', 'FP2-AVE', 'F3-AVE', 'F4-AVE','F7-AVE', 'F8-AVE','Fz-AVE'], 0)
EEGsignal_cleaned_stacked['variable'] = EEGsignal_cleaned_stacked['variable'].replace(['C3-AVE', 'C4-AVE','Cz-AVE'], 1)
EEGsignal_cleaned_stacked['variable'] = EEGsignal_cleaned_stacked['variable'].replace(['T3-AVE', 'T4-AVE', 'T5-AVE', 'T6-AVE'], 2)
EEGsignal_cleaned_stacked['variable'] = EEGsignal_cleaned_stacked['variable'].replace(['P3-AVE', 'P4-AVE', 'O1-AVE', 'O2-AVE', 'Pz-AVE'], 3)

In [71]:
EEGsignal_cleaned_stacked

variable      value
0              0   0.000000
1              0   0.033760
2              0   0.250626
3              0   0.839319
4              0   1.667625
...          ...        ...
280795         3  25.142361
280796         3  19.643417
280797         3  13.450405
280798         3   7.403413
280799         3   2.315274

[280800 rows x 2 columns]

In [93]:
EEGsignal_cleaned_stacked.plot()
plt.show()

In [73]:
print(EEGsignal_cleaned_stacked)

        variable      value
0              0   0.000000
1              0   0.033760
2              0   0.250626
3              0   0.839319
4              0   1.667625
...          ...        ...
280795         3  25.142361
280796         3  19.643417
280797         3  13.450405
280798         3   7.403413
280799         3   2.315274

[280800 rows x 2 columns]


In [15]:
EEGsignal_cleaned_stacked.to_csv('EEGsignal_cleaned_stacked400.csv')

In [16]:
EEGsignal_cleaned_stacked = pd.read_csv('EEGsignal_cleaned_stacked400.csv', index_col = 0)

In [74]:
EEGsignal_cleaned_stacked

variable      value
0              0   0.000000
1              0   0.033760
2              0   0.250626
3              0   0.839319
4              0   1.667625
...          ...        ...
280795         3  25.142361
280796         3  19.643417
280797         3  13.450405
280798         3   7.403413
280799         3   2.315274

[280800 rows x 2 columns]

In [75]:
X = EEGsignal_cleaned_stacked.iloc[:,1]
X = X.to_numpy()
Y = EEGsignal_cleaned_stacked.iloc[:,0]
Y = Y.to_numpy()

In [76]:
Y

array([0, 0, 0, ..., 3, 3, 3], dtype=int64)

In [77]:
X = X.reshape(-1,400)

In [78]:
print(X)

[[ 0.0000000e+00  3.3760000e-02  2.5062600e-01 ... -1.7829600e-01
   6.3985500e-01  1.6757860e+00]
 [ 2.7190970e+00  3.4678900e+00  3.7349770e+00 ... -1.4382860e+00
  -1.1573010e+00 -8.8791500e-01]
 [-6.2448000e-01 -2.6511900e-01  1.8634000e-02 ...  4.7615790e+00
   5.5469570e+00  5.5893580e+00]
 ...
 [ 1.3880418e+01  1.4781011e+01  1.4540157e+01 ...  1.6080326e+01
   2.3348511e+01  2.0894627e+01]
 [ 1.8524021e+01  1.6066433e+01  1.2806382e+01 ... -2.3189050e+00
  -7.1487810e+00 -9.4684820e+00]
 [-1.1014017e+01 -1.4789101e+01 -2.0798380e+01 ...  1.3450405e+01
   7.4034130e+00  2.3152740e+00]]


In [79]:
X.shape

(702, 400)

In [80]:
n0 = np.full((234,),0)
n1 = np.full((117,),1)
n2 = np.full((156,),2)
n3 = np.full((195,),3)

In [81]:
Y = np.concatenate([n0, n1, n2, n3])

In [82]:
print(X.shape)
print(Y.shape)

(702, 400)
(702,)


In [83]:
training_data = []
for x, y in zip(X, Y):
    training_data.append([x,y])

In [27]:
print(training_data)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [84]:
print(len(training_data))

702


In [85]:
import random

random.shuffle(training_data)

In [86]:
for sample in training_data[:30]:
    print(sample[1])

2
2
3
0
2
0
3
3
0
0
0
1
3
2
0
1
1
3
2
0
0
1
0
1
2
1
1
1
0
1


In [87]:
X = []
Y= []

In [88]:
for features, label in training_data:
    X.append(features)
    Y.append(label)

In [89]:
X = np.array(X).reshape(-1, 400, 1)

In [90]:
X.shape

(702, 400, 1)

In [91]:
import pickle

pickle_out = open("X400.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("Y400.pickle","wb")
pickle.dump(Y, pickle_out)
pickle_out.close()

In [49]:
pickle_in = open("X400.pickle","rb")
X = pickle.load(pickle_in)
pickle_in = open("Y400.pickle","rb")
Y = pickle.load(pickle_in)

In [50]:
X

array([[[-5.553167],
        [-4.444186],
        [-3.087638],
        ...,
        [ 7.354341],
        [ 8.184108],
        [ 8.480477]],

       [[ 5.390329],
        [ 5.044119],
        [ 4.447399],
        ...,
        [-6.62418 ],
        [-6.655668],
        [-6.215118]],

       [[ 5.881626],
        [ 5.740934],
        [ 5.795516],
        ...,
        [15.514909],
        [14.758074],
        [13.280252]],

       ...,

       [[ 0.053441],
        [ 2.233593],
        [ 4.157163],
        ...,
        [-7.648946],
        [-6.41491 ],
        [-4.857725]],

       [[ 0.499789],
        [-0.674718],
        [-2.820891],
        ...,
        [ 6.569342],
        [ 3.349689],
        [ 0.93888 ]],

       [[ 3.354211],
        [ 3.752555],
        [ 3.637424],
        ...,
        [ 4.723252],
        [ 5.778434],
        [ 6.753241]]])

In [51]:
print(X.shape[1:])

(400, 1)


numpy.ndarray